services:
  blaze:
    build: 
      context: .
      dockerfile: Dockerfile
    restart: always
    hostname: blaze
    ports:
      - 3000:3000
    volumes:
      - ./config.json:/app/public/config.json
