name: Build the Docker Image
on:
  workflow_dispatch:
  push:
    branches:
    - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Configure Buildx
      id: buildx
      uses: docker/setup-buildx-action@v2

    - name: Login into Docker Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and Push Docker Image
      uses: docker/build-push-action@v3
      with: 
        context: .
        file: Dockerfile
        platforms: linux/amd64, linux/arm64
        builder: ${{ steps.buildx.outputs.name }} 
        push: true
        tags: ghcr.io/vojkovic/blaze:latest

    - name: Logout from GHCR
      run: docker logout ghcr.io